"""create anime table

Revision ID: da3e8c5bb976
Revises: 
Create Date: 2021-08-22 04:23:19.165042

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'da3e8c5bb976'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('animes',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('creation_date', sa.DateTime(), nullable=False),
    sa.Column('modification_date', sa.DateTime(), nullable=True),
    sa.Column('kitsu_id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('season', sa.Enum('WINTER', 'SPRING', 'SUMMER', 'FALL', name='season'), nullable=False),
    sa.Column('status', sa.Enum('TO_BE_ANNOUNCED', 'UNRELEASED', 'UPCOMING', 'CURRENT', 'FINISHED', name='animestatus'), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('synopsis', sa.String(), nullable=True),
    sa.Column('cover_image', sa.String(), nullable=True),
    sa.Column('poster_image', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', 'kitsu_id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_animes_id'), 'animes', ['id'], unique=False)
    op.create_index(op.f('ix_animes_kitsu_id'), 'animes', ['kitsu_id'], unique=False)
    op.create_index(op.f('ix_animes_slug'), 'animes', ['slug'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_animes_slug'), table_name='animes')
    op.drop_index(op.f('ix_animes_kitsu_id'), table_name='animes')
    op.drop_index(op.f('ix_animes_id'), table_name='animes')
    op.drop_table('animes')
    # ### end Alembic commands ###
